[package]
name = "cassandra_tes"
version = "0.1.0"
edition = "2024"

[dependencies]
cassandra-cpp = "3.0.2"
tokio = { version = "1.48.0", features = ["full"] }
[build]
rustflags = ["-L", "/opt/homebrew/opt/cassandra-cpp-driver/lib", "-L", "/opt/homebrew/opt/openssl@3/lib"]

